version: '3.7'

services:
  huxchain:
    image: huxchain
    restart: unless-stopped
    build:
      context: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000

  huxchain-2:
    image: huxchain
    restart: unless-stopped
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
